### ISSUE TITLE
🤷‍♂️ use $theme-colors map to modify colors

### ISSUE THREAD

**Issue by m5o** [ThemesGuide/top-hat#1]
Hey ho 🙌

I did some testing today and only wanted to share that I could only get proper theme colors by using the `$theme-colors` syntax for [Wandoo](https://tophat.github.io/themes/dist/wandoo/):

```scss
/*! Whootstrap `Wandoo` Bootstrap 4.1.1 theme */
// https://tophat.github.io/themes/dist/wandoo/
@import url('//fonts.googleapis.com/css?family=Nunito:200,300,400,700');
$font-family-base: Nunito;
@import url('//fonts.googleapis.com/css?family=Comfortaa:200,300,400,700');
$headings-font-family: Comfortaa;

$theme-colors: (
  "primary": #ff304f,
  "secondary": #cacaca,
  "success": #015668,
  "danger": #06648c,
  "info": #0f81c7,
  "warning": #0de2ea,
  "light": #ececec,
  "dark": #222222
);

@import "bootstrap";
```

Only the setup of `$primary`, `$secondary`, `$success`, … didn't get me the result I expected.

* 🎨 https://getbootstrap.com/docs/4.1/getting-started/theming/
* 📝 https://getbootstrap.com/docs/4.1/getting-started/theming/#modify-map
* ⚙️ https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss#L84

**Comment by ThemesGuide** [comment]
Modifying the color variable should also work. Do you have an example/snippet that demonstrates the unexpected result?

**Comment by m5o** [comment]
I used the feature to loop trough the `$theme-colors` often. If the color are only set on their named variable this doesn't apply to the `$theme-colors` array.

As a result the `$primary`, `$secondary`… color from the default theme is used.

```scss
@mixin hero-variant($color, $text-color: $body-bg) {
  background-color: $color;
  color: $text-color;

  &.hero-filter {
    background-image: linear-gradient(135deg, darken($color, 2), lighten($color, 10) 75%);
  }
}

@each $color, $value in $theme-colors {
  .hero-#{$color} {
    @include hero-variant($value);
  }
}
```
